# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(89f685dc-04cb-4d5e-9aa4-631f86de3b44)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(89f685dc-04cb-4d5e-9aa4-631f86de3b44)'
    subscriptionId: '89f685dc-04cb-4d5e-9aa4-631f86de3b44'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AngularAssignment'
    location: 'East Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'SchoolApp'
    deploymentMode: 'Incremental'
      appType: 'webApp'
      WebAppName: 'BharathiVidyalaSchoolApps'
      packageForLinux: 'dist/FsmsApp'